services:
  _defaults:
    bind:
      Psr\Log\LoggerInterface $logger: '@logger'
      $d3AppName: '%env(D3_APP_NAME)%'

security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    users_in_memory: { memory: null }
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      id: App\security\UserProvider
    interAppUser:
      entity:
        class: 'App\security\User'
        property: 'tenantId'
  firewalls:
    dev:
      pattern: ^/%d3_app_name%/(_(profiler|wdt)|css|images|js)/
      security: false
    stage:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    lifecycle:
      pattern: ^/%d3_app_name%/dvelop-cloud-lifecycle-event
      security: false
    interAppIdentityProvider:
      pattern: ^/%d3_app_name%/interappauthenticationcallback
      security: false
    userIdentityProvider:
      pattern: ^/%d3_app_name%/userauthenticationcallback
      security: false
    upservice:
      pattern: ^/%d3_app_name%/upservice
      security: false
    index:
      anonymous: true
      provider: interAppUser
      pattern: ^/%d3_app_name%(/|)$
      guard:
        authenticators:
          - Liondeer\Security\InterAppD3ecmAuthenticator
    indexFeature:
      anonymous: true
      provider: interAppUser
      pattern: ^/%d3_app_name%/(configfeatures|features|dmsobjectextensions)$
      guard:
        authenticators:
          - Liondeer\Security\InterAppD3ecmAuthenticator
    D3webhook:
      anonymous: false
      pattern: ^/%d3_app_name%/webhook/document/create
      provider: interAppUser
      guard:
        authenticators:
          - App\security\D3WebhookAuthenticator
        entry_point: Liondeer\Security\D3ecmAuthenticator
    SmartInvoiceWebhook:
      anonymous: false
      pattern: ^/%d3_app_name%/webhook/(document/smartinvoice|data)
      provider: interAppUser
      guard:
        authenticators:
          - App\security\SmartInvoiceWebhookAuthenticator
        entry_point: App\security\SmartInvoiceWebhookAuthenticator
    main:
      anonymous: false
      lazy: true
      provider: users_in_memory
      guard:
        authenticators:
          - Liondeer\Security\D3ecmAuthenticator
      stateless: true
    translation:
      pattern: ^/%d3_app_name%/translation.js
      security: false
