parameters:
  app_env: '%env(string:APP_ENV)%'
  d3_app_name: '%env(string:D3_APP_NAME)%'
  d3_app_secret: '%env(string:D3_APP_SECRET)%'
  app_default_locale: '%env(string:APP_DEFAULT_LOCALE)%'
  d3_database_url: '%env(secret:D3_APP_NAME)%'

services:
  aws_env_var_processor:
    class: Liondeer\Framework\DependencyInjection\AwsEnvVarProcessor
    tags: ['container.env_var_processor']

security:
  providers:
    users_in_memory: { memory: null }
    dms_user:
      id: Liondeer\Framework\Security\D3UserProvider
    inter_app_user:
      id: Liondeer\Framework\Security\InterAppProvider

  # Der folgende Firewall-Block überschreibt den in config/packages/security.yaml definierten block.
  # Sollte keine Authentifizierung über d.velop User gewünscht sein kann dieser Block hier auskommentiert werden,
  # um wieder den Symfony Standart zu nutzen. Wenn allerdings nur einzelne Bereiche ohne d.velop
  # Authentifizierung aufrufbar sein sollen können neue Firewall regeln hinzugefügt werden.
  # siehe https://symfony.com/doc/current/security.html#the-firewall
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    stage:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    lifecycle:
      pattern: ^/%d3_app_name%/dvelop-cloud-lifecycle-event
      security: false
    interAppIdentityProvider:
      pattern: ^/%d3_app_name%/interappauthenticationcallback
      security: false
    userIdentityProvider:
      pattern: ^/%d3_app_name%/userauthenticationcallback
      security: false
    upservice:
      pattern: ^/%d3_app_name%/upservice
      security: false
    translation:
      pattern: ^/%d3_app_name%/translation.js
      security: false
    sources:
      pattern: ^/%d3_app_name%/sources
      security: false
    index:
      pattern: ^/%d3_app_name%(/|)$
      security: false
    indexFeature:
      pattern: ^/%d3_app_name%/(configfeatures|features|dmsobjectextensions)$
      provider: inter_app_user
      custom_authenticators:
        - Liondeer\Framework\Security\InterAppAuthenticator
    main:
      lazy: true
      provider: dms_user

twig:
  form_themes: ['materializecss_layout.html.twig']
  globals:
    APP_ENV: '%env(APP_ENV)%'
    D3_APP_NAME: '%env(D3_APP_NAME)%'



